generate models
Impulse73/task_manage_dualboot pull request #10
Opened 2021-04-10 09:29 UTC by Impulse73

2021-04-12 14:34 UTC, Andrew8xx8 requested changes

2021-04-12 14:34 UTC, Andrew8xx8 commented on test/factories/tasks.rb
> +    name { "MyString" }
Все фабрики нужно поправить так, чтобы значения генерировались автоматически, а не были заданными жёстко

2021-04-12 14:34 UTC, Andrew8xx8 commented on test/models/task_test.rb
> +require "test_helper"
Пустые тесты надо удалить

2021-04-12 14:34 UTC, Andrew8xx8 commented on test/models/admin_test.rb
> +  test "create" do
Тесты на модели не нужны, они ничего не проверяют

2021-04-14 17:53 UTC, Impulse73 commented on test/factories/tasks.rb
> +    name { "MyString" }
Исправил

2021-04-14 17:53 UTC, Impulse73 commented on test/models/task_test.rb
> +require "test_helper"
исправил

2021-04-14 17:53 UTC, Impulse73 commented on test/models/admin_test.rb
> +  test "create" do
Ответил в телеграмме

2021-04-15 16:55 UTC, greybutton commented on test/factories/users.rb
> +  end
посмотри в упражнении код внимательней, нужно только тип разный указать. полностью копировать не нужно, в этом фишка, что только одно поле меняем

```
FactoryBot.define do
  factory :user do
    first_name
    last_name
    password
    email { "MyString" }
    avatar { "MyString" }
    type { "" }
  end

  factory :developer do
    type { "Developer" }
  end
end
```

2021-04-19 07:37 UTC, greybutton approved these changes

2021-04-19 16:00 UTC, merged