add state machine for task model
Impulse73/task_manage_dualboot pull request #12
Opened 2021-04-21 19:36 UTC by Impulse73

2021-04-22 16:12 UTC, greybutton requested changes

2021-04-22 16:12 UTC, greybutton commented on app/models/task.rb
> +      if :new_task
где такое нашел с ифами?) посмотри доку https://github.com/state-machines/state_machines

2021-04-22 16:12 UTC, greybutton commented on app/models/task.rb
> +    state :archived
тоже можно не объявлять так с этим гемом

2021-04-22 16:12 UTC, greybutton commented on app/models/task.rb
> +    end
где то есть иф, где то нет. хоть ифы в целом не верно, интересно выглядит, что где то их добавил, где то нет)

2021-04-24 08:30 UTC, Impulse73 commented on app/models/task.rb
> +    end
Исправил)

2021-04-26 09:02 UTC, Andrew8xx8 requested changes

2021-04-26 09:02 UTC, Andrew8xx8 commented on app/models/task.rb
> +  state_machine :initial => :new_task do
Тут не по стйлгайду хеш указан, надо `initial: :new_task`. Запусти `rubocop -a` внутри контейнера — автоматически все исправит.

2021-04-26 15:23 UTC, Impulse73 commented on app/models/task.rb
> +  state_machine :initial => :new_task do
Исправил

2021-04-26 15:33 UTC, Andrew8xx8 approved these changes

2021-04-26 15:34 UTC, greybutton approved these changes

2021-04-26 16:00 UTC, merged